# Generated by Django 4.2.7 on 2025-11-26 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_eventfavorite',
                'indexes': [models.Index(fields=['user'], name='events_even_user_id_6b96df_idx'), models.Index(fields=['event'], name='events_even_event_i_4a6c43_idx'), models.Index(fields=['created_at'], name='events_even_created_797444_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
