# Generated by Django 4.2.7 on 2025-11-26 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_eventfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('invitation_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_eventinvitation',
                'indexes': [models.Index(fields=['event'], name='events_even_event_i_c8d784_idx'), models.Index(fields=['inviter'], name='events_even_inviter_b0a520_idx'), models.Index(fields=['invitee'], name='events_even_invitee_e19c99_idx'), models.Index(fields=['invitation_code'], name='events_even_invitat_88fb51_idx'), models.Index(fields=['status'], name='events_even_status_4a554f_idx')],
                'unique_together': {('event', 'invitee')},
            },
        ),
    ]
