# Generated by Django 4.2.7 on 2025-11-27 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_managed_university'),
        ('events', '0003_eventinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='university',
            field=models.ForeignKey(blank=True, help_text="Université associée à l'événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.university'),
        ),
    ]
