# Generated by Django 4.2.7 on 2025-11-27 03:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Image de l'événement", max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url_legacy',
            field=models.URLField(blank=True, help_text="Ancienne URL de l'image (pour migration)", max_length=500),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['university'], name='events_even_univers_eaa8eb_idx'),
        ),
    ]
