# Generated by Django 4.2.7 on 2025-11-28 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_remove_event_image_url_event_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('link', 'Link Copy'), ('other', 'Other')], default='link', max_length=20)),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_eventshare',
                'indexes': [models.Index(fields=['event'], name='events_even_event_i_99c1f7_idx'), models.Index(fields=['user'], name='events_even_user_id_2f8a9b_idx'), models.Index(fields=['shared_at'], name='events_even_shared__ae9943_idx')],
            },
        ),
    ]
