# Generated by Django 4.2.7 on 2025-11-28 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_eventshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFilterPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this filter set', max_length=100)),
                ('filters', models.JSONField(default=dict, help_text='Filter parameters (category, date_range, price_range, location, etc.)')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as default filter set')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_filter_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Filter Preference',
                'verbose_name_plural': 'Event Filter Preferences',
                'db_table': 'events_eventfilterpreference',
                'indexes': [models.Index(fields=['user'], name='events_even_user_id_458400_idx'), models.Index(fields=['is_default'], name='events_even_is_defa_016a44_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
