# Generated by Django 4.2.7 on 2025-11-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_created', 'Événement créé'), ('event_reminder', 'Rappel événement'), ('event_invitation', 'Invitation à un événement'), ('participation', 'Participation'), ('comment', 'Commentaire'), ('like', 'Like'), ('friend_request', "Demande d'ami"), ('friend_request_accepted', "Demande d'ami acceptée"), ('message', 'Message'), ('message_broadcast', 'Message broadcast'), ('group_invitation', 'Invitation à un groupe'), ('group_post', 'Nouveau post dans un groupe'), ('account_activated', 'Compte activé'), ('account_deactivated', 'Compte désactivé'), ('class_leader_promoted', 'Promu responsable de classe'), ('system', 'Système')], max_length=50),
        ),
    ]
