# Generated by Django 4.2.7 on 2025-11-26 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(db_index=True, max_length=50)),
                ('content_id', models.UUIDField(db_index=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harcèlement'), ('inappropriate', 'Contenu inapproprié'), ('fake', 'Faux'), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examiné'), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_report',
                'indexes': [models.Index(fields=['reporter'], name='moderation__reporte_6f6e5c_idx'), models.Index(fields=['content_type', 'content_id'], name='moderation__content_1b6680_idx'), models.Index(fields=['status'], name='moderation__status_3fc7e7_idx'), models.Index(fields=['created_at'], name='moderation__created_7bb7e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='moderation__user_id_12f991_idx'), models.Index(fields=['action_type'], name='moderation__action__abda91_idx'), models.Index(fields=['created_at'], name='moderation__created_10ab9a_idx')],
            },
        ),
    ]
