# Generated by Django 4.2.7 on 2025-11-26 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('profile_image', models.URLField(blank=True, max_length=500)),
                ('university', models.CharField(blank=True, db_index=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('members_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('events_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('moderator', 'Modérateur'), ('member', 'Membre'), ('invited', 'Invité')], db_index=True, default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente'), ('banned', 'Banni'), ('left', 'Parti')], db_index=True, default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_membership',
                'indexes': [models.Index(fields=['group'], name='groups_memb_group_i_1dc648_idx'), models.Index(fields=['user'], name='groups_memb_user_id_adc2a6_idx'), models.Index(fields=['role'], name='groups_memb_role_db1074_idx'), models.Index(fields=['status'], name='groups_memb_status_89d232_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('post_type', models.CharField(default='text', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='groups.group')),
            ],
            options={
                'db_table': 'groups_grouppost',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group'], name='groups_grou_group_i_96ff1a_idx'), models.Index(fields=['author'], name='groups_grou_author__cc866a_idx'), models.Index(fields=['created_at'], name='groups_grou_created_1d4a00_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['creator'], name='groups_grou_creator_cc7cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['university'], name='groups_grou_univers_074f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_public'], name='groups_grou_is_publ_f37341_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_verified'], name='groups_grou_is_veri_96b2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['slug'], name='groups_grou_slug_246a6a_idx'),
        ),
    ]
