# Generated by Django 4.2.7 on 2025-11-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_managed_university'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='group',
            new_name='groups_grou_univers_0b5f40_idx',
            old_name='groups_grou_univers_074f4f_idx',
        ),
        migrations.AddField(
            model_name='group',
            name='university_name_legacy',
            field=models.CharField(blank=True, help_text='Ancien nom (pour migration)', max_length=200),
        ),
        # First, remove the old CharField university
        migrations.RemoveField(
            model_name='group',
            name='university',
        ),
        # Then add the new ForeignKey university
        migrations.AddField(
            model_name='group',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Université associée au groupe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='users.university'),
        ),
    ]
