# Generated by Django 4.2.7 on 2025-11-27 03:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_groups_grou_univers_074f4f_idx_groups_grou_univers_0b5f40_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover_image_url_legacy',
            field=models.URLField(blank=True, help_text="Ancienne URL de l'image de couverture (pour migration)", max_length=500),
        ),
        migrations.AddField(
            model_name='group',
            name='profile_image_url_legacy',
            field=models.URLField(blank=True, help_text="Ancienne URL de l'image de profil (pour migration)", max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image de couverture du groupe', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='group',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image de profil du groupe', max_length=255, null=True, verbose_name='image'),
        ),
    ]
