# Generated by Django 4.2.7 on 2025-12-01 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_group_cover_image_url_legacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='groups.grouppost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_grouppostlike',
                'indexes': [models.Index(fields=['post'], name='groups_grou_post_id_847c30_idx'), models.Index(fields=['user'], name='groups_grou_user_id_a16ef4_idx')],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupPostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='groups.grouppost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_grouppostcomment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['post'], name='groups_grou_post_id_cb638c_idx'), models.Index(fields=['user'], name='groups_grou_user_id_81480c_idx')],
            },
        ),
    ]
