# Generated by Django 4.2.7 on 2025-11-26 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who deleted this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden by admin moderation'),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approuvé'), ('pending', 'En attente'), ('rejected', 'Rejeté'), ('hidden', 'Masqué')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_hidden'], name='social_post_is_hidd_a49ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_deleted'], name='social_post_is_dele_1320a6_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['moderation_status'], name='social_post_moderat_4fae82_idx'),
        ),
    ]
