# Generated by Django 4.2.7 on 2025-11-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group associated with this conversation (only for group conversations)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='groups.group'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['group'], name='messaging_c_group_i_9d07f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('conversation_type', 'group'), ('group__isnull', False)), ('conversation_type', 'private'), _connector='OR'), name='group_conversation_must_have_group'),
        ),
    ]
