# Generated by Django 4.2.7 on 2025-11-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_group_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='group_conversation_must_have_group',
        ),
    ]
