# Generated by Django 4.2.7 on 2025-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_for_all',
            field=models.BooleanField(default=False, help_text='Message deleted for all participants'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='User has archived this conversation'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, help_text='User has marked this conversation as favorite'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, help_text='User has pinned this conversation'),
        ),
        migrations.AddField(
            model_name='participant',
            name='mute_notifications',
            field=models.BooleanField(default=False, help_text='User has muted notifications for this conversation'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_pinned'], name='messaging_p_is_pinn_45d66c_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_archived'], name='messaging_p_is_arch_c95127_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_favorite'], name='messaging_p_is_favo_f1c199_idx'),
        ),
    ]
