# Generated by Django 4.2.7 on 2025-11-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
