# Generated by Django 4.2.7 on 2025-11-26 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Reason for ban'),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who banned this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_banned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, help_text='For temporary bans', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
