# Generated by Django 4.2.7 on 2025-11-27 02:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def _save_legacy_university_names(apps, schema_editor):
    """Save current university CharField values to legacy field before migration."""
    Profile = apps.get_model('users', 'Profile')
    # Copy university (CharField) to university_name_legacy before altering
    for profile in Profile.objects.all():
        if profile.university and profile.university.strip():
            profile.university_name_legacy = profile.university
            profile.save(update_fields=['university_name_legacy'])
        else:
            # Set empty string to avoid issues
            profile.university_name_legacy = ''
            profile.save(update_fields=['university_name_legacy'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ban_reason_user_banned_at_user_banned_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Nom officiel de l'université", max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Slug pour les URLs', unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Nom court (ex: ESMT, UCAD)', max_length=50)),
                ('email_domains', models.JSONField(default=list, help_text="Domaines email autorisés (ex: ['@esmt.sn', '@esmt.sn.dakar'])")),
                ('logo', models.URLField(blank=True, help_text="URL du logo de l'université", max_length=500)),
                ('cover_image', models.URLField(blank=True, help_text="URL de l'image de couverture", max_length=500)),
                ('description', models.TextField(blank=True, help_text="Description de l'université")),
                ('website', models.URLField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True, help_text="Adresse de l'université")),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Université active ou non')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Université',
                'verbose_name_plural': 'Universités',
                'db_table': 'users_university',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='users_profi_univers_7b2b1e_idx',
            old_name='users_profi_univers_4bc2e7_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='university_name_legacy',
            field=models.CharField(blank=True, help_text='Ancien nom (pour migration)', max_length=200),
        ),
        migrations.RunPython(
            code=_save_legacy_university_names,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['name'], name='users_unive_name_a0e109_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['slug'], name='users_unive_slug_6757b8_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['is_active'], name='users_unive_is_acti_1c8818_idx'),
        ),
        # First, remove the old CharField university
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        # Then add the new ForeignKey university
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, help_text="Université de l'étudiant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.university'),
        ),
    ]
