# Generated by Django 4.2.7 on 2025-11-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_university',
            field=models.ForeignKey(blank=True, help_text='Université gérée par cet administrateur (si role=university_admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='users.university'),
        ),
    ]
