# Generated by Django 4.2.7 on 2025-11-27 03:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def _save_legacy_campus_names(apps, schema_editor):
    """Save current campus CharField values to legacy field before migration."""
    Profile = apps.get_model('users', 'Profile')
    # Copy campus (CharField) to campus_name_legacy before altering
    for profile in Profile.objects.all():
        if profile.campus and profile.campus.strip():
            profile.campus_name_legacy = profile.campus
            profile.save(update_fields=['campus_name_legacy'])
        else:
            profile.campus_name_legacy = ''
            profile.save(update_fields=['campus_name_legacy'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_managed_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='campus_name_legacy',
            field=models.CharField(blank=True, help_text='Ancien nom de campus (pour migration)', max_length=200),
        ),
        migrations.RunPython(
            code=_save_legacy_campus_names,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Nom du campus (ex: Campus Principal, Campus Dakar)', max_length=200)),
                ('slug', models.SlugField(help_text='Slug pour les URLs')),
                ('address', models.TextField(blank=True, help_text='Adresse complète du campus')),
                ('city', models.CharField(blank=True, db_index=True, help_text='Ville du campus', max_length=100)),
                ('country', models.CharField(default='Sénégal', help_text='Pays du campus', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email de contact du campus', max_length=254)),
                ('is_main', models.BooleanField(db_index=True, default=False, help_text="Campus principal de l'université")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Campus actif ou non')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude GPS', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude GPS', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(help_text='Université à laquelle appartient ce campus', on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='users.university')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'db_table': 'users_campus',
                'ordering': ['-is_main', 'name'],
            },
        ),
        # First, remove the old CharField campus
        migrations.RemoveField(
            model_name='profile',
            name='campus',
        ),
        # Then add the new ForeignKey campus
        migrations.AddField(
            model_name='profile',
            name='campus',
            field=models.ForeignKey(blank=True, help_text="Campus de l'étudiant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.campus'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['university'], name='users_campu_univers_f129dd_idx'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['name'], name='users_campu_name_a15dad_idx'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['city'], name='users_campu_city_4e72bf_idx'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['is_main'], name='users_campu_is_main_51ceb3_idx'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['is_active'], name='users_campu_is_acti_b1c32b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('university', 'slug')},
        ),
    ]
