# Generated by Django 4.2.7 on 2025-11-27 03:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_campus_name_legacy_campus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Nom du département/filière (ex: Informatique, Mathématiques)', max_length=200)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Code du département (ex: INFO, MATH)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description du département')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Département actif ou non')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(help_text='Université à laquelle appartient ce département', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.university')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'users_department',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['university'], name='users_depar_univers_13e32b_idx'), models.Index(fields=['name'], name='users_depar_name_30ebb2_idx'), models.Index(fields=['code'], name='users_depar_code_872430_idx'), models.Index(fields=['is_active'], name='users_depar_is_acti_1b6176_idx')],
                'unique_together': {('university', 'code')},
            },
        ),
    ]
