# Generated by Django 4.2.7 on 2025-11-27 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Département/Filière de l'étudiant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='field_of_study_legacy',
            field=models.CharField(blank=True, help_text='Ancien nom de filière (pour migration)', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='Ancien champ (pour migration)', max_length=200),
        ),
    ]
