# Generated by Django 4.2.7 on 2025-11-27 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_department_profile_field_of_study_legacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(db_index=True, help_text='Année académique (ex: 2024-2025)', max_length=20)),
                ('start_date', models.DateField(help_text="Date de début de l'année académique")),
                ('end_date', models.DateField(help_text="Date de fin de l'année académique")),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='Année académique actuelle')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Année académique active ou non')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(help_text='Université à laquelle appartient cette année académique', on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='users.university')),
            ],
            options={
                'verbose_name': 'Année Académique',
                'verbose_name_plural': 'Années Académiques',
                'db_table': 'users_academic_year',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['university'], name='users_acade_univers_b8bb58_idx'), models.Index(fields=['year'], name='users_acade_year_870926_idx'), models.Index(fields=['is_current'], name='users_acade_is_curr_355dcc_idx'), models.Index(fields=['is_active'], name='users_acade_is_acti_ccb28a_idx')],
                'unique_together': {('university', 'year')},
            },
        ),
    ]
