# Generated by Django 4.2.7 on 2025-11-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_year_legacy',
            field=models.CharField(blank=True, help_text='Ancienne année académique (pour migration)', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_year_obj',
            field=models.ForeignKey(blank=True, help_text="Année académique de l'étudiant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.academicyear'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Ancien champ (pour migration)', max_length=50),
        ),
    ]
