# Generated by Django 4.2.7 on 2025-11-27 03:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_academic_year_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='cover_image_url_legacy',
            field=models.URLField(blank=True, help_text="Ancienne URL de l'image de couverture (pour migration)", max_length=500),
        ),
        migrations.AddField(
            model_name='university',
            name='logo_url_legacy',
            field=models.URLField(blank=True, help_text='Ancienne URL du logo (pour migration)', max_length=500),
        ),
        migrations.AlterField(
            model_name='university',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Image de couverture de l'université", max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Logo de l'université", max_length=255, null=True, verbose_name='image'),
        ),
    ]
