# Generated by Django 4.2.7 on 2025-11-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_university_cover_image_url_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo du campus', null=True, upload_to='campus_images/'),
        ),
    ]
