# Generated by Django 4.2.7 on 2025-11-27 03:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_campus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('require_email_verification', models.BooleanField(default=True, help_text="Exiger la vérification de l'email lors de l'inscription")),
                ('require_phone_verification', models.BooleanField(default=False, help_text='Exiger la vérification du numéro de téléphone')),
                ('auto_verify_students', models.BooleanField(default=False, help_text="Vérifier automatiquement les étudiants lors de l'inscription")),
                ('require_admin_approval', models.BooleanField(default=True, help_text="Exiger l'approbation d'un administrateur pour activer les comptes")),
                ('moderate_posts', models.BooleanField(default=True, help_text='Modérer les posts avant publication')),
                ('moderate_events', models.BooleanField(default=False, help_text='Modérer les événements avant publication')),
                ('moderate_groups', models.BooleanField(default=False, help_text='Modérer les groupes avant publication')),
                ('allow_student_groups', models.BooleanField(default=True, help_text='Permettre aux étudiants de créer des groupes')),
                ('allow_student_events', models.BooleanField(default=True, help_text='Permettre aux étudiants de créer des événements')),
                ('max_groups_per_student', models.IntegerField(default=5, help_text="Nombre maximum de groupes qu'un étudiant peut créer")),
                ('send_welcome_email', models.BooleanField(default=True, help_text='Envoyer un email de bienvenue aux nouveaux étudiants')),
                ('send_verification_email', models.BooleanField(default=True, help_text='Envoyer un email lors de la vérification du compte')),
                ('send_event_reminders', models.BooleanField(default=True, help_text='Envoyer des rappels pour les événements')),
                ('show_phone_numbers', models.BooleanField(default=False, help_text='Afficher les numéros de téléphone dans les profils publics')),
                ('show_email_addresses', models.BooleanField(default=False, help_text='Afficher les adresses email dans les profils publics')),
                ('primary_color', models.CharField(default='#3B82F6', help_text="Couleur primaire de l'université (hex)", max_length=7)),
                ('secondary_color', models.CharField(default='#8B5CF6', help_text="Couleur secondaire de l'université (hex)", max_length=7)),
                ('custom_css', models.TextField(blank=True, help_text="CSS personnalisé pour l'université")),
                ('academic_year_start_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=9, help_text="Mois de début de l'année académique (1-12)")),
                ('academic_year_end_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=6, help_text="Mois de fin de l'année académique (1-12)")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.OneToOneField(help_text='Université associée à ces paramètres', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.university')),
            ],
            options={
                'verbose_name': "Paramètres d'Université",
                'verbose_name_plural': "Paramètres d'Universités",
                'db_table': 'users_university_settings',
            },
        ),
    ]
