# Generated by Django 4.2.7 on 2025-12-02 18:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_department_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_36d76d_idx',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image du campus', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Code du département (ex: INFO, GC)', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, help_text='Nom du département (ex: Informatique, Génie Civil)', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('class_leader', 'Responsable de Classe'), ('association', 'Association/Club'), ('sponsor', 'Partenaire/Sponsor'), ('admin', 'Administrateur'), ('university_admin', "Administrateur d'Université")], default='student', max_length=20),
        ),
    ]
