# Generated by Django 4.2.7 on 2025-11-26 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('event', 'Événement'), ('group', 'Groupe'), ('announcement', 'Annonce'), ('news', 'Actualité')], default='news', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='feed_images/')),
                ('visibility', models.CharField(choices=[('public', 'Publique'), ('private', 'Privée (École)')], default='public', help_text="Publique: visible par tous. Privée: visible uniquement par les étudiants de l'école de l'auteur", max_length=10)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_feeditem',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feed_feedit_created_d2e023_idx'), models.Index(fields=['author', '-created_at'], name='feed_feedit_author__b4c247_idx'), models.Index(fields=['visibility', 'university', '-created_at'], name='feed_feedit_visibil_2f230e_idx')],
            },
        ),
    ]
