# Generated by Django 4.2.7 on 2025-11-26 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_alter_feeditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who deleted this feed item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden by admin moderation'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approuvé'), ('pending', 'En attente'), ('rejected', 'Rejeté'), ('hidden', 'Masqué')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['is_hidden'], name='feed_feedit_is_hidd_07faf6_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['is_deleted'], name='feed_feedit_is_dele_7f9cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['moderation_status'], name='feed_feedit_moderat_905aff_idx'),
        ),
    ]
